server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

  # /actuator/info endpoint config
  # Git information is also shown, based on the git.properties file produced during the build and packaged with the app
  info:
    git:
      mode: full

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

graphiql:
  subscriptions:
    timeout: 30000